#!/bin/sh

cd ~

# Log WLR errors and logs to the hyprland log. Recommended
export HYPRLAND_LOG_WLR=1

# Tell XWayland to use a cursor theme
export XCURSOR_THEME=Breeze_Snow

# Set a cursor size
export XCURSOR_SIZE=24

# Example IME Support: fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

export WLR_NO_HARDWARE_CURSORS=1

# Execute Hyprland
if [ -f /usr/local/bin/Hyprland ]; then
   exec /usr/local/bin/Hyprland >/dev/null 2>&1 
elif [ -f /usr/bin/Hyprland ]; then
   exec /usr/bin/Hyprland >/dev/null 2>&1 
fi
