# theme = "Catppuccin"

[[colors.indexed_colors]]
color = "0xF8BD96"
index = 16

[[colors.indexed_colors]]
color = "0xF5E0DC"
index = 17

[colors.bright]
black = "0x988BA2"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.cursor]
cursor = "0xF5E0DC"
text = "0x1E1D2F"

[colors.normal]
black = "0x6E6C7E"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.primary]
background = "0x1E1D2F"
foreground = "0xD9E0EE"

[font]
size = 12

[font.bold]
family = "Caskaydia Cove NF"
style = "Bold"

[font.bold_italic]
family = "Caskaydia Cove NF"
style = "Bold Italic"

[font.italic]
family = "Caskaydia Cove NF"
style = "Italic"

[font.normal]
family = "Caskaydia Cove NF"
style = "Regular"

[font.offset]
x = 0
y = 0
