require("options")
require("keymaps")
require("autocommands")
require("lsp")

require("plugins.mini-nvim")
require("plugins.colorscheme")
require("plugins.treesitter")
require("plugins.zen")
require("plugins.fidget")
require("plugins.conform")
require("plugins.oil")
require("plugins.shipwright")
require("plugins.blink")
require("plugins.harpoon")
require("plugins.nvim-lint")
